version: "3.9"
services:
  app1:
    build: .
    image: pr5-simple-app:latest
    environment: [ NAME_APP=app1 ]
    volumes: [ uploads:/upload-files ]
    restart: on-failure
  app2:
    image: pr5-simple-app:latest
    environment: [ NAME_APP=app2 ]
    volumes: [ uploads:/upload-files ]
    restart: on-failure
  app3:
    image: pr5-simple-app:latest
    environment: [ NAME_APP=app3 ]
    volumes: [ uploads:/upload-files ]
    restart: on-failure
  app4:
    image: pr5-simple-app:latest
    environment: [ NAME_APP=app4 ]
    volumes: [ uploads:/upload-files ]
    restart: on-failure
  proxy:
    image: nginx:1.25
    ports: [ "80:80" ]
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [ app1, app2, app3, app4 ]
    restart: on-failure
volumes:
  uploads:
