# ниже для пр4
#
#spring:
#  rsocket:
#    server:
#      transport: tcp
#      port: 7777
#  r2dbc:
#    url: r2dbc:h2:mem:///pr4db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#logging:
#  level:
#    root: INFO

# ниже для пр5
server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  codec:
    max-in-memory-size: 32MB
app:
  name: ${NAME_APP:app}
  upload-path: /upload-files
logging:
  level:
    io.netty: WARN
