spring:
  rsocket:
    server:
      transport: tcp
      port: 7777
  r2dbc:
    url: r2dbc:h2:mem:///pr4db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
logging:
  level:
    root: INFO
