CREATE TABLE IF NOT EXISTS reading (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       type VARCHAR(16) NOT NULL,
                                       val INT NOT NULL,
                                       ts TIMESTAMP NOT NULL
);
